services:
  postgres:
    image: postgres:17
    container_name: smallsupermarket-postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smallsupermarket_database
    volumes:
      - smallsupermarket_postgres_data:/var/lib/postgresql/data

volumes:
  smallsupermarket_postgres_data:
