DROP TABLE IF EXISTS stocks;

DROP TABLE IF EXISTS skus;

DROP TABLE IF EXISTS units;

DROP TABLE IF EXISTS brands;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS positions;

DROP TABLE IF EXISTS roles;

DROP TABLE IF EXISTS branches;