definitions:
  gin.H:
    additionalProperties: {}
    type: object
  supermarket-backend_internal_dto.BranchResponse:
    properties:
      address:
        type: string
      branch_id:
        type: string
      branch_name:
        type: string
    type: object
  supermarket-backend_internal_dto.CreateBranchRequest:
    properties:
      address:
        maxLength: 150
        type: string
      branch_name:
        maxLength: 100
        type: string
    required:
    - address
    - branch_name
    type: object
  supermarket-backend_internal_dto.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  supermarket-backend_internal_dto.LoginResponse:
    properties:
      access_token:
        type: string
      user:
        $ref: '#/definitions/supermarket-backend_internal_dto.UserResponse'
    type: object
  supermarket-backend_internal_dto.PositionResponse:
    properties:
      position_id:
        type: string
      position_name:
        type: string
    type: object
  supermarket-backend_internal_dto.RoleResponse:
    properties:
      created_at:
        type: string
      role_id:
        type: string
      role_name:
        type: string
      updated_at:
        type: string
    type: object
  supermarket-backend_internal_dto.UpdateBranchRequest:
    properties:
      address:
        maxLength: 150
        type: string
      branch_name:
        maxLength: 100
        type: string
    type: object
  supermarket-backend_internal_dto.UserResponse:
    properties:
      branch:
        $ref: '#/definitions/supermarket-backend_internal_dto.BranchResponse'
      email:
        type: string
      full_name:
        type: string
      phone_number:
        type: string
      position:
        $ref: '#/definitions/supermarket-backend_internal_dto.PositionResponse'
      role:
        $ref: '#/definitions/supermarket-backend_internal_dto.RoleResponse'
      status:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: SmallSupermarket APIs
  title: SmallSupermarket APIs
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and set the access token in an HttpOnly cookie
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/supermarket-backend_internal_dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/supermarket-backend_internal_dto.LoginResponse'
        "400":
          description: Invalid request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: User login
      tags:
      - Auth
  /auth/me:
    get:
      description: Get information of the currently authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/supermarket-backend_internal_dto.UserResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - CookieAuth: []
      summary: Get current user
      tags:
      - Auth
  /branches:
    get:
      description: Get all branches
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/supermarket-backend_internal_dto.BranchResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get all branches
      tags:
      - branches
    post:
      consumes:
      - application/json
      description: Create a new branch
      parameters:
      - description: Create branch request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/supermarket-backend_internal_dto.CreateBranchRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/supermarket-backend_internal_dto.BranchResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Create branch
      tags:
      - branches
  /branches/{branch_id}:
    delete:
      description: Delete a branch by its ID
      parameters:
      - description: Branch ID
        in: path
        name: branch_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Delete branch
      tags:
      - branches
    get:
      description: Get a branch by its ID
      parameters:
      - description: Branch ID
        in: path
        name: branch_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/supermarket-backend_internal_dto.BranchResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get branch by ID
      tags:
      - branches
    put:
      consumes:
      - application/json
      description: Update an existing branch
      parameters:
      - description: Branch ID
        in: path
        name: branch_id
        required: true
        type: string
      - description: Update branch request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/supermarket-backend_internal_dto.UpdateBranchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/supermarket-backend_internal_dto.BranchResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Update branch
      tags:
      - branches
  /positions:
    get:
      description: Get all positions
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/supermarket-backend_internal_dto.PositionResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get all positions
      tags:
      - positions
  /positions/{position_id}:
    get:
      description: Get a position by its ID
      parameters:
      - description: Position ID
        in: path
        name: position_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/supermarket-backend_internal_dto.PositionResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get position by ID
      tags:
      - positions
  /roles:
    get:
      description: Get all roles
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/supermarket-backend_internal_dto.RoleResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get all roles
      tags:
      - roles
  /roles/{role_id}:
    get:
      description: Get a role by its ID
      parameters:
      - description: Role ID
        in: path
        name: role_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/supermarket-backend_internal_dto.RoleResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get role by ID
      tags:
      - roles
securityDefinitions:
  CookieAuth:
    in: cookie
    name: access_token
    type: apiKey
swagger: "2.0"
