definitions:
  supermarket-backend_internal_dto.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  supermarket-backend_internal_dto.LoginResponse:
    properties:
      access_token:
        type: string
      user:
        $ref: '#/definitions/supermarket-backend_internal_dto.UserResponse'
    type: object
  supermarket-backend_internal_dto.UserResponse:
    properties:
      branch_id:
        type: string
      email:
        type: string
      full_name:
        type: string
      phone_number:
        type: string
      position_id:
        type: string
      role_id:
        type: string
      status:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: SmallSupermarket APIs
  title: SmallSupermarket APIs
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return an access token
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/supermarket-backend_internal_dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/supermarket-backend_internal_dto.LoginResponse'
        "400":
          description: Invalid request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: User login
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
